-- ===============================================================
-- Projeto:       SolarMetrics 2.0
-- Sprint:        3 - DDL (tabelas, PK/FK, comentários)
-- Execução:      Primeiro script da cadeia (ver README.md)
-- ===============================================================

CREATE SEQUENCE SEQ_SM_AUDITORIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE SM_USUARIO (
    ID_USER         VARCHAR2(36)   NOT NULL,
    NOME_COMPLETO   VARCHAR2(200)  NOT NULL,
    EMAIL           VARCHAR2(200)  NOT NULL,
    SENHA_HASH      VARCHAR2(200),
    STATUS          VARCHAR2(20)   DEFAULT 'ATIVO' NOT NULL,
    CONSTRAINT PK_SM_USUARIO PRIMARY KEY (ID_USER),
    CONSTRAINT UK_SM_USUARIO_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE SM_USUARIO IS 'Usuários responsáveis pelos sistemas solares.';
COMMENT ON COLUMN SM_USUARIO.ID_USER IS 'Identificador único do usuário.';
COMMENT ON COLUMN SM_USUARIO.EMAIL IS 'E-mail único no sistema.';

CREATE TABLE SM_END_SISTEMA (
    ID_END_SIS   VARCHAR2(36)   NOT NULL,
    LOGRADOURO   VARCHAR2(200)  NOT NULL,
    CIDADE       VARCHAR2(100)  NOT NULL,
    UF           VARCHAR2(2)    NOT NULL,
    CEP          VARCHAR2(12),
    CONSTRAINT PK_SM_END_SISTEMA PRIMARY KEY (ID_END_SIS)
);

COMMENT ON TABLE SM_END_SISTEMA IS 'Endereço da instalação solar.';

CREATE TABLE SM_SISTEMA (
    ID_SISTEMA                  VARCHAR2(36)   NOT NULL,
    NOME_INSTALACAO             VARCHAR2(200)  NOT NULL,
    DATA_INSTALACAO             DATE           NOT NULL,
    POTENCIA_TOTAL              NUMBER(12,2)   NOT NULL,
    STATUS                      VARCHAR2(50)   NOT NULL,
    SM_USUARIO_ID_USER          VARCHAR2(36)   NOT NULL,
    SM_END_SISTEMA_ID_END_SIS   VARCHAR2(36)   NOT NULL,
    CONSTRAINT PK_SM_SISTEMA PRIMARY KEY (ID_SISTEMA),
    CONSTRAINT FK_SIS_USUARIO FOREIGN KEY (SM_USUARIO_ID_USER)
        REFERENCES SM_USUARIO (ID_USER),
    CONSTRAINT FK_SIS_END FOREIGN KEY (SM_END_SISTEMA_ID_END_SIS)
        REFERENCES SM_END_SISTEMA (ID_END_SIS)
);

COMMENT ON TABLE SM_SISTEMA IS 'Sistema de geração solar monitorado.';
COMMENT ON COLUMN SM_SISTEMA.POTENCIA_TOTAL IS 'Potência instalada total (ex.: kWp).';

CREATE TABLE SM_SENSOR (
    ID_SENSOR                VARCHAR2(36)   NOT NULL,
    TIPO                     VARCHAR2(50)   NOT NULL,
    STATUS                   VARCHAR2(50)   NOT NULL,
    LOCALIZACAO              VARCHAR2(200),
    SM_SISTEMA_ID_SISTEMA    VARCHAR2(36)   NOT NULL,
    CONSTRAINT PK_SM_SENSOR PRIMARY KEY (ID_SENSOR),
    CONSTRAINT FK_SENSOR_SISTEMA FOREIGN KEY (SM_SISTEMA_ID_SISTEMA)
        REFERENCES SM_SISTEMA (ID_SISTEMA)
);

COMMENT ON TABLE SM_SENSOR IS 'Sensores vinculados a um sistema.';

CREATE TABLE SM_PAINEL_SOLAR (
    ID_PAINEL                VARCHAR2(36)   NOT NULL,
    MODELO                   VARCHAR2(100)  NOT NULL,
    CAPACIDADE_KWP           NUMBER(10,2)   NOT NULL,
    QTD_PANEIS               NUMBER(10)     NOT NULL,
    SM_SISTEMA_ID_SISTEMA    VARCHAR2(36)   NOT NULL,
    CONSTRAINT PK_SM_PAINEL_SOLAR PRIMARY KEY (ID_PAINEL),
    CONSTRAINT FK_PAINEL_SISTEMA FOREIGN KEY (SM_SISTEMA_ID_SISTEMA)
        REFERENCES SM_SISTEMA (ID_SISTEMA)
);

COMMENT ON TABLE SM_PAINEL_SOLAR IS 'Painéis por sistema.';

CREATE TABLE SM_MANUTENCAO (
    ID_MANUTENCAO            VARCHAR2(36)   NOT NULL,
    DATA_AGENDADA            DATE           NOT NULL,
    DESCRICAO                VARCHAR2(500),
    STATUS                   VARCHAR2(50)   NOT NULL,
    SM_SISTEMA_ID_SISTEMA    VARCHAR2(36)   NOT NULL,
    CONSTRAINT PK_SM_MANUTENCAO PRIMARY KEY (ID_MANUTENCAO),
    CONSTRAINT FK_MAN_SISTEMA FOREIGN KEY (SM_SISTEMA_ID_SISTEMA)
        REFERENCES SM_SISTEMA (ID_SISTEMA)
);

COMMENT ON TABLE SM_MANUTENCAO IS 'Manutenções agendadas ou realizadas.';

CREATE TABLE SM_MONITORAMENTO (
    ID_MONITORAMENTO         VARCHAR2(36)   NOT NULL,
    DATA_HORA                TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    VALOR_LEITURA            NUMBER(14,4)   NOT NULL,
    UNIDADE                  VARCHAR2(20)   NOT NULL,
    SM_SENSOR_ID_SENSOR      VARCHAR2(36)   NOT NULL,
    CONSTRAINT PK_SM_MONITORAMENTO PRIMARY KEY (ID_MONITORAMENTO),
    CONSTRAINT FK_MON_SENSOR FOREIGN KEY (SM_SENSOR_ID_SENSOR)
        REFERENCES SM_SENSOR (ID_SENSOR)
);

COMMENT ON TABLE SM_MONITORAMENTO IS 'Leituras dos sensores.';

CREATE TABLE SM_AUDITORIA (
    ID_AUDITORIA     NUMBER         NOT NULL,
    NOME_TABELA      VARCHAR2(128)  NOT NULL,
    OPERACAO         VARCHAR2(10)   NOT NULL,
    USUARIO_ORACLE   VARCHAR2(128)  NOT NULL,
    DATA_OPERACAO    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    DADOS_OLD        CLOB,
    DADOS_NEW        CLOB,
    CONSTRAINT PK_SM_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT CK_SM_AUD_OPERACAO CHECK (OPERACAO IN ('INSERT', 'UPDATE', 'DELETE'))
);

COMMENT ON TABLE SM_AUDITORIA IS 'Auditoria OLD/NEW (Sprint 3).';
