-- ===============================================================
-- Projeto:       SolarMetrics 2.0
-- Sprint:        3 - Roteiro de testes / vídeo
-- Ordem:         01 → 02 → 04 → 05 → 06 → este arquivo
-- ===============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED FORMAT WRAPPED;

PROMPT === FN_JSON_LINHA_SISTEMA_SENSOR (sucesso) ===
SELECT FN_JSON_LINHA_SISTEMA_SENSOR(
    'SX', 'Usina Teste "Aspas"', 100.5, 'ATIVO',
    'SY', 'IRRADIANCIA', 'ATIVO', 'Telhado "A"'
) AS JSON_RESULT FROM DUAL;

PROMPT === FN_JSON (parâmetro nulo) ===
SELECT FN_JSON_LINHA_SISTEMA_SENSOR(
    NULL, 'X', 1, 'ATIVO', 'S1', 'T', 'ATIVO', 'L'
) AS JSON_ERRO FROM DUAL;

PROMPT === FN_VALIDAR_POTENCIA_SISTEMA ===
SELECT FN_VALIDAR_POTENCIA_SISTEMA(150) FROM DUAL;
SELECT FN_VALIDAR_POTENCIA_SISTEMA(0) FROM DUAL;
SELECT FN_VALIDAR_POTENCIA_SISTEMA(NULL) FROM DUAL;
SELECT FN_VALIDAR_POTENCIA_SISTEMA(2000000) FROM DUAL;

PROMPT === PROC_RELATORIO_SISTEMA_SENSOR_JSON ===
BEGIN
    PROC_RELATORIO_SISTEMA_SENSOR_JSON;
END;
/

PROMPT === PROC_RELATORIO_POTENCIA_ANT_ATUAL_PROX ===
BEGIN
    PROC_RELATORIO_POTENCIA_ANT_ATUAL_PROX;
END;
/

PROMPT === DML para auditoria (INSERT/UPDATE/DELETE) ===
INSERT INTO SM_SISTEMA (
    ID_SISTEMA, NOME_INSTALACAO, DATA_INSTALACAO,
    POTENCIA_TOTAL, STATUS, SM_USUARIO_ID_USER, SM_END_SISTEMA_ID_END_SIS
) VALUES (
    'S_AUD_1', 'Usina Auditoria INSERT', DATE '2025-03-28',
    100, 'ATIVO', 'U1', 'END1'
);
COMMIT;

UPDATE SM_SISTEMA
SET POTENCIA_TOTAL = 120, STATUS = 'MANUTENCAO'
WHERE ID_SISTEMA = 'S_AUD_1';
COMMIT;

DELETE FROM SM_SISTEMA WHERE ID_SISTEMA = 'S_AUD_1';
COMMIT;

PROMPT === SM_AUDITORIA (últimos 10) ===
SELECT *
FROM (
    SELECT ID_AUDITORIA,
           NOME_TABELA,
           OPERACAO,
           USUARIO_ORACLE,
           DATA_OPERACAO,
           DBMS_LOB.SUBSTR(DADOS_OLD, 200, 1) AS OLD_PREVIEW,
           DBMS_LOB.SUBSTR(DADOS_NEW, 200, 1) AS NEW_PREVIEW
    FROM SM_AUDITORIA
    ORDER BY ID_AUDITORIA DESC
)
WHERE ROWNUM <= 10;
